name: taxi-nyc

services:
  db:
    container_name: taxi-db
    hostname: taxi
    image: postgres:latest
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always
    volumes:
      - taxi-db:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  taxi-db:
